name: learn_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

#  flutter_gallery_assets:
#    git:
#      url: https://flutter.googlesource.com/gallery-assets
#      ref: d318485f208376e06d7e330d9f191141d14722b8

dev_dependencies:

  args: 1.3.0 # TRANSITIVE DEPENDENCY
  async: 2.0.4 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+14 # TRANSITIVE DEPENDENCY
  boolean_selector: 1.0.2 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  cli_util: 0.1.2+1 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  csslib: 0.14.1 # TRANSITIVE DEPENDENCY
  file: 2.3.6 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  html: 0.13.2+2 # TRANSITIVE DEPENDENCY
  http: 0.11.3+16 # TRANSITIVE DEPENDENCY
  http_multi_server: 2.0.4 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  io: 0.3.2+1 # TRANSITIVE DEPENDENCY
  isolate: 1.1.0 # TRANSITIVE DEPENDENCY
  js: 0.6.1 # TRANSITIVE DEPENDENCY
  json_rpc_2: 2.0.7 # TRANSITIVE DEPENDENCY
  logging: 0.11.3+1 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  meta: 1.1.2 # TRANSITIVE DEPENDENCY
  mime: 0.9.6 # TRANSITIVE DEPENDENCY
  mockito: 2.2.3 # TRANSITIVE DEPENDENCY
  multi_server_socket: 1.0.1 # TRANSITIVE DEPENDENCY
  node_preamble: 1.4.0 # TRANSITIVE DEPENDENCY
  package_config: 1.0.3 # TRANSITIVE DEPENDENCY
  package_resolver: 1.0.2 # TRANSITIVE DEPENDENCY
#    path: 1.5.1 # TRANSITIVE DEPENDENCY
  plugin: 0.2.0+2 # TRANSITIVE DEPENDENCY
  pool: 1.3.4 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  quiver: 0.28.0 # TRANSITIVE DEPENDENCY
  shelf: 0.7.2 # TRANSITIVE DEPENDENCY
  shelf_packages_handler: 1.0.3 # TRANSITIVE DEPENDENCY
  shelf_static: 0.2.7 # TRANSITIVE DEPENDENCY
  shelf_web_socket: 0.2.2 # TRANSITIVE DEPENDENCY
  source_map_stack_trace: 1.1.4 # TRANSITIVE DEPENDENCY
  source_maps: 0.10.4 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stack_trace: 1.9.1 # TRANSITIVE DEPENDENCY
  stream_channel: 1.6.3 # TRANSITIVE DEPENDENCY
  term_glyph: 1.0.0 # TRANSITIVE DEPENDENCY
#  test: 0.12.30+4 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.5 # TRANSITIVE DEPENDENCY
  utf: 0.9.0+4 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY
  vm_service_client: 0.2.4+1 # TRANSITIVE DEPENDENCY
  watcher: 0.9.7+7 # TRANSITIVE DEPENDENCY
  web_socket_channel: 1.0.7 # TRANSITIVE DEPENDENCY
  yaml: 2.1.13 # TRANSITIVE DEPENDENCY


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
       - assets/images/appbar/appbar_background_layer0.png
       - assets/images/appbar/appbar_background_layer1.png
       - assets/images/appbar/appbar_background_layer2.png
       - assets/images/appbar/appbar_background_layer3.png
       - assets/images/appbar/appbar_background_layer4.png
       - assets/images/appbar/appbar_background_layer5.png
       - assets/images/shrine/products/backpack.png
       - assets/images/shrine/products/beachball.png
       - assets/images/shrine/products/binoculars.png
       - assets/images/shrine/products/brush.png
       - assets/images/shrine/products/chair.png
       - assets/images/shrine/products/chucks.png
       - assets/images/shrine/products/clock.png
       - assets/images/shrine/products/fish_bowl.png
       - assets/images/shrine/products/flippers.png
       - assets/images/shrine/products/green-shoes.png
       - assets/images/shrine/products/heels.png
       - assets/images/shrine/products/helmet.png
       - assets/images/shrine/products/lawn_chair.png
       - assets/images/shrine/products/lipstick.png
       - assets/images/shrine/products/popsicle.png
       - assets/images/shrine/products/radio.png
       - assets/images/shrine/products/sunnies.png
       - assets/images/shrine/products/surfboard.png
       - assets/images/shrine/products/teapot.png
       - assets/images/shrine/vendors/16c477b.jpg
       - assets/images/shrine/vendors/ali-connors.png
       - assets/images/shrine/vendors/peter-carlsson.png
       - assets/images/shrine/vendors/sandra-adams.jpg
       - assets/images/shrine/vendors/zach.jpg
#    - lib/gallery/example_code.dart
#    - assets/images/animated_flutter_lgtm.gif
#    - assets/images/animated_flutter_stickers.webp
#    - assets/images/appbar_background.jpg
#    - assets/images/appbar/appbar_background_layer0.png
#    - assets/images/appbar/appbar_background_layer1.png
#    - assets/images/appbar/appbar_background_layer2.png
#    - assets/images/appbar/appbar_background_layer3.png
#    - assets/images/appbar/appbar_background_layer4.png
#    - assets/images/appbar/appbar_background_layer5.png
#    - assets/images/pesto/avatar.jpg
#    - assets/images/pesto/image10.jpg
#    - assets/images/pesto/image11.jpg
#    - assets/images/pesto/image12.jpg
#    - assets/images/pesto/image13.jpg
#    - assets/images/pesto/image1.jpg
#    - assets/images/pesto/image2.jpg
#    - assets/images/pesto/image3.jpg
#    - assets/images/pesto/image4.jpg
#    - assets/images/pesto/image5.jpg
#    - assets/images/pesto/image6.jpg
#    - assets/images/pesto/image7.jpg
#    - assets/images/pesto/image8.jpg
#    - assets/images/pesto/image9.jpg
#    - assets/images/pesto/logo_small.png
#    - assets/images/pesto/logo_medium.png
#    - assets/images/pesto/fish.png
#    - assets/images/pesto/healthy.png
#    - assets/images/pesto/main.png
#    - assets/images/pesto/meat.png
#    - assets/images/pesto/quick.png
#    - assets/images/pesto/spicy.png
#    - assets/images/pesto/veggie.png
#    - assets/images/about_logo.png
#    - assets/images/ali_connors.jpg
#    - assets/images/drawer_logo.png
#    - assets/images/kangaroo_valley_safari.jpg
#    - assets/images/top_10_australian_beaches.jpg
#    - assets/images/landscape_0.jpg
#    - assets/images/landscape_1.jpg
#    - assets/images/landscape_2.jpg
#    - assets/images/landscape_3.jpg
#    - assets/images/landscape_4.jpg
#    - assets/images/landscape_5.jpg
#    - assets/images/landscape_6.jpg
#    - assets/images/landscape_7.jpg
#    - assets/images/landscape_8.jpg
#    - assets/images/landscape_9.jpg
#    - assets/images/landscape_10.jpg
#    - assets/images/landscape_11.jpg

#    - assets/images/cupertino_navigation/person1.jpg
#    - assets/images/cupertino_navigation/person2.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/images/pesto/fonts/Raleway-Regular.ttf
        - asset: assets/images/pesto/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/images/pesto/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/shrine/AbrilFatface-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
